### ISSUE TITLE
Error when editing audio message [minor]

### ISSUE THREAD

**Issue by norz** [smcclennon/SongID#1]
SongID worked well to recognize the song from the audio message, however when I edited the audio message to add additional information for myself, the bot detected the change, and output an error message: 
“ ⚠️ An error occured, sorry for any inconvenience caused.
The developer has been notified and will look into this issue as soon as possible.”

**Comment by norz** [comment]
PS: thanks 🙏 again for the bot, it’s very useful! 👍 😊.

**Comment by smcclennon** [comment]
Could you please provide me with the date and time the error occured, along with your timezone?

**Comment by norz** [comment]
Sure! Here is one: 2020-05-09 12:38 UTC+3
(Not the original occurrence, but a reproduction of the behavior.)

(Sorry for thé late reply, I was away from my mailbox.)

**Comment by smcclennon** [comment]
Added attribute checks to avoid attempting to send message contents of a message which has been edited to the developer (commit [#49b05f5](https://github.com/smcclennon/SongID/commit/49b05f5))
