### ISSUE TITLE
No response

### ISSUE THREAD

**Issue by github-account1111** [smcclennon/SongID#6]
In the past when I would send audio the bot would either link the track, let me know it couldn't find it or say it's hit the daily limit.
Now I just get no response.

**Comment by smcclennon** [comment]
Thanks for letting me know. I've restarted the bot and it is now working again :)

It appears to have become stuck when communicating with ACRCloud via their SDK. I have updated the SDK on my server which may help prevent this from occurring in future.

**Comment by BieHDC** [comment]
Still seems to be broken. As you can see i tried it twice, the help command works, the mydata command does nothing.
![stillbroken](https://user-images.githubusercontent.com/43303168/151042779-928186a3-2c11-46b5-b19f-6b5ecd6d64b3.png)

**Comment by github-account1111** [comment]
Can't reproduce on my end.
`/mydata` returns the correct results.
Sending audio also returns a response.

Are you using a VPN?

**Comment by smcclennon** [comment]
I also cannot reproduce this, and `/mydata` works for me too.

@BieHDC Please send your username to [@SongIDsupportbot](https://t.me/SongIDsupportbot) along with reference "BieHDC". Your username will allow me to locate your requests in SongID logs and possibly find the problem.

**Comment by BieHDC** [comment]
> I also cannot reproduce this, and `/mydata` works for me too.
> 
> @BieHDC Please send your username to [@SongIDsupportbot](https://t.me/SongIDsupportbot) along with reference "BieHDC". Your username will allow me to locate your requests in SongID logs and possibly find the problem.

Any luck so far?

**Comment by smcclennon** [comment]
I think the logs of your issue have already been rotated. Please reproduce the issue and let me know once you have so I can take another look.

**Comment by BieHDC** [comment]
> I think the logs of your issue have already been rotated. Please reproduce the issue and let me know once you have so I can take another look.

Done. I would like to add that my messages are marked as read by the bot and that it was broken from me from the very beginning.

**Comment by smcclennon** [comment]
I just noticed that your Telegram username and ID were not present in the userdata file. I have restarted the bot.

An error has also just come in with your Telegram ID to do with a `KeyError` in the userdata file. Could you try sending the bot `/start` so it refreshes your userdata?

**Comment by BieHDC** [comment]
> I just noticed that your Telegram username and ID were not present in the userdata file. I have restarted the bot.
> 
> An error has also just come in with your Telegram ID to do with a `KeyError` in the userdata file. Could you try sending the bot `/start` so it refreshes your userdata?

Now it works and it also finds the sample song. Thanks.
So..what exactly was the issue then? It just didnt add me to the database when i invited it?

**Comment by smcclennon** [comment]
SongID depends on the user initially sending `/start` which is when it would check if your Telegram ID is in the database, and if not it will use it to create a key in the database with blank data.
https://github.com/smcclennon/SongID/blob/b34894c7d345e2532e5c16fbb8a1f1f01f019d36/SongID.py#L131-L134

SongID then continuously updates your user data each time you send it a file.
https://github.com/smcclennon/SongID/blob/312bf1afba9eb6a995c8dd694905de634d813aaa/SongIDProcessor.py#L41-L43

SongID did not have your Telegram ID in its database so when you would try to use `/mydata` it failed to fetch your data, and when you tried to send a file, it failed to check if you were surpassing the 20 second cooldown.

Here is where it would attempt to access `userdata[your_telegram_id]`, and it would fail so the rest of the code for your request would not be executed, which includes the code which sends you a message.
https://github.com/smcclennon/SongID/blob/312bf1afba9eb6a995c8dd694905de634d813aaa/SongIDProcessor.py#L222

**Comment by BieHDC** [comment]
> SongID depends on the user initially sending `/start` which is when it would check if your Telegram ID is in the database, and if not it will use it to create a key in the database with blank data.

Ok, so this is my fault then, i did not know that. However it also did not tell me to and that command is also not in the list. ![pic](https://user-images.githubusercontent.com/43303168/151660699-6e3ea37d-8a43-4a0c-9d87-5e7d918e0b1d.png)

I assume that is standard knowledge for people using telegram bots more? It would certainly be nice if that was mentioned somewhere. And maybe throw an error to the user if he did not do that yet.

**Comment by smcclennon** [comment]
I thought you were forced to send `/start` when you first message a bot which is why I designed it to work like that. 

I have made a change to check if user data exists before getting user data which should silently solve this problem without the user needing to do anything https://github.com/smcclennon/SongID/commit/bf123ed6dcd8780d9fab028eb30eb101fa5c29f2.

**Comment by github-account1111** [comment]
>I thought you were forced to send /start when you first message a bot

You're right, I think that's a button you press before you're able to send any messages.

**Comment by BieHDC** [comment]
> > I thought you were forced to send /start when you first message a bot
> 
> You're right, I think that's a button you press before you're able to send any messages.

Then how was i able to send messages straight away? The only reason i can think of would be the telegram-web-client having a bug.

**Comment by smcclennon** [comment]
I have started bots in the past without sending `/start` as my first message, but I can't remember how.

Even if the bot was offline at the time, if you started the bot with `/start`, SongID would have processed that command once it was back online as Telegram stores messages in a queue which bots poll from.

It could have been a client bug which may have been fixed by now.
